from .Apple import AppleAPI
from .Carbon import CarbonAPI
from .Resso import RessoAPI
from .Soundcloud import SoundAPI
from .SongCache import SongCacheAPI
from .Spotify import SpotifyAPI
from .Telegram import TeleAPI
from .TgScrap import TgScrapAPI
from .Youtube import YouTubeAPI
